//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decore.ClientApp.AlcoholServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlcoholServiceReference.IAlcoholService")]
    public interface IAlcoholService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/GetBeverage", ReplyAction="http://tempuri.org/IAlcoholService/GetBeverageResponse")]
        Decore.Models.Beverage[] GetBeverage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/GetBeverage", ReplyAction="http://tempuri.org/IAlcoholService/GetBeverageResponse")]
        System.Threading.Tasks.Task<Decore.Models.Beverage[]> GetBeverageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/GetBeverageById", ReplyAction="http://tempuri.org/IAlcoholService/GetBeverageByIdResponse")]
        Decore.Models.Beverage GetBeverageById(int beverageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/GetBeverageById", ReplyAction="http://tempuri.org/IAlcoholService/GetBeverageByIdResponse")]
        System.Threading.Tasks.Task<Decore.Models.Beverage> GetBeverageByIdAsync(int beverageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/CreateBeverage", ReplyAction="http://tempuri.org/IAlcoholService/CreateBeverageResponse")]
        void CreateBeverage(Decore.Models.Beverage beverageObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlcoholService/CreateBeverage", ReplyAction="http://tempuri.org/IAlcoholService/CreateBeverageResponse")]
        System.Threading.Tasks.Task CreateBeverageAsync(Decore.Models.Beverage beverageObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlcoholServiceChannel : Decore.ClientApp.AlcoholServiceReference.IAlcoholService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlcoholServiceClient : System.ServiceModel.ClientBase<Decore.ClientApp.AlcoholServiceReference.IAlcoholService>, Decore.ClientApp.AlcoholServiceReference.IAlcoholService {
        
        public AlcoholServiceClient() {
        }
        
        public AlcoholServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlcoholServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlcoholServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlcoholServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Decore.Models.Beverage[] GetBeverage() {
            return base.Channel.GetBeverage();
        }
        
        public System.Threading.Tasks.Task<Decore.Models.Beverage[]> GetBeverageAsync() {
            return base.Channel.GetBeverageAsync();
        }
        
        public Decore.Models.Beverage GetBeverageById(int beverageId) {
            return base.Channel.GetBeverageById(beverageId);
        }
        
        public System.Threading.Tasks.Task<Decore.Models.Beverage> GetBeverageByIdAsync(int beverageId) {
            return base.Channel.GetBeverageByIdAsync(beverageId);
        }
        
        public void CreateBeverage(Decore.Models.Beverage beverageObject) {
            base.Channel.CreateBeverage(beverageObject);
        }
        
        public System.Threading.Tasks.Task CreateBeverageAsync(Decore.Models.Beverage beverageObject) {
            return base.Channel.CreateBeverageAsync(beverageObject);
        }
    }
}
