//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decore.ClientApp.ScheduleServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeEventInfo", Namespace="http://schemas.datacontract.org/2004/07/ScheduleService")]
    [System.SerializableAttribute()]
    public partial class EmployeeEventInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivingAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Decore.Models.Event EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LeavingAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivingAt {
            get {
                return this.ArrivingAtField;
            }
            set {
                if ((this.ArrivingAtField.Equals(value) != true)) {
                    this.ArrivingAtField = value;
                    this.RaisePropertyChanged("ArrivingAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Decore.Models.Event Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LeavingAt {
            get {
                return this.LeavingAtField;
            }
            set {
                if ((this.LeavingAtField.Equals(value) != true)) {
                    this.LeavingAtField = value;
                    this.RaisePropertyChanged("LeavingAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScheduleServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isRunning", ReplyAction="http://tempuri.org/IService1/isRunningResponse")]
        bool isRunning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isRunning", ReplyAction="http://tempuri.org/IService1/isRunningResponse")]
        System.Threading.Tasks.Task<bool> isRunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeSchedule", ReplyAction="http://tempuri.org/IService1/GetEmployeeScheduleResponse")]
        Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo[] GetEmployeeSchedule(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEmployeeSchedule", ReplyAction="http://tempuri.org/IService1/GetEmployeeScheduleResponse")]
        System.Threading.Tasks.Task<Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo[]> GetEmployeeScheduleAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AttendEmployeeToEvent", ReplyAction="http://tempuri.org/IService1/AttendEmployeeToEventResponse")]
        Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo AttendEmployeeToEvent(int employeeId, int eventId, System.DateTime arrivingAt, System.DateTime leavingAt, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AttendEmployeeToEvent", ReplyAction="http://tempuri.org/IService1/AttendEmployeeToEventResponse")]
        System.Threading.Tasks.Task<Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo> AttendEmployeeToEventAsync(int employeeId, int eventId, System.DateTime arrivingAt, System.DateTime leavingAt, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        string AddEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEvent", ReplyAction="http://tempuri.org/IService1/AddEventResponse")]
        System.Threading.Tasks.Task<string> AddEventAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveEvent", ReplyAction="http://tempuri.org/IService1/RemoveEventResponse")]
        string RemoveEvent(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveEvent", ReplyAction="http://tempuri.org/IService1/RemoveEventResponse")]
        System.Threading.Tasks.Task<string> RemoveEventAsync(int eventId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Decore.ClientApp.ScheduleServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Decore.ClientApp.ScheduleServiceReference.IService1>, Decore.ClientApp.ScheduleServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isRunning() {
            return base.Channel.isRunning();
        }
        
        public System.Threading.Tasks.Task<bool> isRunningAsync() {
            return base.Channel.isRunningAsync();
        }
        
        public Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo[] GetEmployeeSchedule(int employeeId) {
            return base.Channel.GetEmployeeSchedule(employeeId);
        }
        
        public System.Threading.Tasks.Task<Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo[]> GetEmployeeScheduleAsync(int employeeId) {
            return base.Channel.GetEmployeeScheduleAsync(employeeId);
        }
        
        public Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo AttendEmployeeToEvent(int employeeId, int eventId, System.DateTime arrivingAt, System.DateTime leavingAt, string comment) {
            return base.Channel.AttendEmployeeToEvent(employeeId, eventId, arrivingAt, leavingAt, comment);
        }
        
        public System.Threading.Tasks.Task<Decore.ClientApp.ScheduleServiceReference.EmployeeEventInfo> AttendEmployeeToEventAsync(int employeeId, int eventId, System.DateTime arrivingAt, System.DateTime leavingAt, string comment) {
            return base.Channel.AttendEmployeeToEventAsync(employeeId, eventId, arrivingAt, leavingAt, comment);
        }
        
        public string AddEvent(int eventId) {
            return base.Channel.AddEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<string> AddEventAsync(int eventId) {
            return base.Channel.AddEventAsync(eventId);
        }
        
        public string RemoveEvent(int eventId) {
            return base.Channel.RemoveEvent(eventId);
        }
        
        public System.Threading.Tasks.Task<string> RemoveEventAsync(int eventId) {
            return base.Channel.RemoveEventAsync(eventId);
        }
    }
}
