// <auto-generated />
namespace Decore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tableCountDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tableCountDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201705302220498_tableCountDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
